# Generated by Django 5.0.7 on 2024-10-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_event_image_eventattachment_event_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('selected_event', models.CharField(max_length=255)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_dob', models.DateField(blank=True, null=True)),
                ('vaccination_card', models.FileField(blank=True, null=True, upload_to='vaccination_cards/')),
                ('agree_to_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
